import XCTest
import EventKit
@testable import MoriPhotos

final class LunarCalendarTests: XCTestCase {
    private func lunar(_ date: String, zone: String = "Asia/Shanghai", hour: Int = 12) -> LunarCalendarDate {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: zone)!
        let parts = date.split(separator: "-").map { Int($0)! }
        let value = calendar.date(from: DateComponents(year: parts[0], month: parts[1], day: parts[2], hour: hour))!
        return CalendarLayout(calendar: calendar).lunarDate(on: value)
    }
    // Independent dates from HKO conversion tables, rather than values generated by the implementation.
    // https://www.hko.gov.hk/en/gts/time/calendar/pdf/files/2026e.pdf (and 2023e / 2024e / 2025e)
    func testKnownLunarDatesAndFestivals() {
        XCTAssertEqual(lunar("2026-02-17").description, "农历正月初一 · 春节")
        XCTAssertEqual(lunar("2026-06-19").description, "农历五月初五 · 端午")
        XCTAssertEqual(lunar("2026-09-25").description, "农历八月十五 · 中秋")
        XCTAssertEqual(lunar("2026-09-11").label, "八月")
        XCTAssertEqual(lunar("2026-09-30").label, "二十")
        XCTAssertEqual(lunar("2026-10-01").label, "廿一")
    }
    func testLeapMonthNamesAndNoDuplicatedFestival() {
        XCTAssertEqual(lunar("2025-07-25").label, "闰六月")
        XCTAssertEqual(lunar("2025-08-08").description, "农历闰六月十五")
        XCTAssertTrue(lunar("2023-03-23").isLeapMonth)
        XCTAssertEqual(lunar("2023-02-21").festival, "龙抬头")
        XCTAssertNil(lunar("2023-03-23").festival, "Leap second month must not repeat the festival")
    }
    func testNewYearsEveOnBothShortAndLongMonths() {
        XCTAssertEqual(lunar("2024-02-09").description, "农历腊月三十 · 除夕")
        XCTAssertEqual(lunar("2025-01-28").description, "农历腊月廿九 · 除夕")
        XCTAssertEqual(lunar("2026-02-16").festival, "除夕")
        XCTAssertNil(lunar("2026-02-15").festival)
    }
    func testDisplayedCivilDayStaysConsistentAcrossZonesAndTimes() {
        let expected = lunar("2026-09-25")
        for zone in ["Asia/Shanghai", "America/Los_Angeles", "Pacific/Auckland"] {
            for hour in [0, 12, 23] {
                XCTAssertEqual(lunar("2026-09-25", zone: zone, hour: hour), expected, "\(zone), \(hour)")
            }
        }
    }
}

final class CalendarLayoutTests: XCTestCase {
    private func layout(_ zone: String = "Asia/Shanghai") -> CalendarLayout {
        var c = Calendar(identifier: .gregorian); c.timeZone = TimeZone(identifier: zone)!
        return CalendarLayout(calendar: c)
    }
    private func date(_ value: String) -> Date { ISO8601DateFormatter().date(from: value)! }
    private func event(_ start: String, _ end: String, allDay: Bool = false, title: String = "测试") -> CalendarOccurrence {
        CalendarOccurrence(eventIdentifier: "series", calendarItemIdentifier: "series", calendarID: "calendar", title: title,
            start: date(start), end: date(end), isAllDay: allDay, location: "", hasRecurrence: false)
    }
    func testLeapMonthAndSixWeekMonthCoverWholeWeeksStartingMonday() {
        let l = layout()
        let feb = l.days(in: date("2024-02-12T12:00:00+08:00"))
        XCTAssertEqual(feb.count, 35)
        XCTAssertEqual(l.dayID(feb.first!), "2024-01-29"); XCTAssertEqual(l.dayID(feb.last!), "2024-03-03")
        let march = l.days(in: date("2026-03-10T12:00:00+08:00"))
        XCTAssertEqual(march.count, 42)
        XCTAssertEqual(l.dayID(march.first!), "2026-02-23"); XCTAssertEqual(l.dayID(march.last!), "2026-04-05")
    }
    func testAllDayEndIsExclusiveAndMidnightEndDoesNotLeakIntoNextDay() {
        let l = layout(), day = date("2026-09-13T12:00:00+08:00")
        let allDay = event("2026-09-12T00:00:00+08:00", "2026-09-13T00:00:00+08:00", allDay: true)
        let midnight = event("2026-09-12T23:00:00+08:00", "2026-09-13T00:00:00+08:00")
        let crossing = event("2026-09-12T23:00:00+08:00", "2026-09-13T01:00:00+08:00")
        XCTAssertEqual(l.events([allDay, midnight, crossing], on: day), [crossing])
        XCTAssertEqual(l.events([allDay, midnight, crossing], on: l.addingDays(-1, to: day)).count, 3)
    }
    func testDaylightSavingUsesCalendarDaysInsteadOf86400Seconds() {
        let l = layout("America/Los_Angeles")
        let spring = l.day(containing: date("2026-03-08T12:00:00-07:00"))
        let fall = l.day(containing: date("2026-11-01T12:00:00-08:00"))
        XCTAssertEqual(l.addingDays(1, to: spring).timeIntervalSince(spring), 23 * 3600)
        XCTAssertEqual(l.addingDays(1, to: fall).timeIntervalSince(fall), 25 * 3600)
        let late = event("2026-03-08T23:30:00-07:00", "2026-03-09T00:00:00-07:00")
        XCTAssertEqual(l.events([late], on: spring).count, 1)
        XCTAssertTrue(l.events([late], on: l.addingDays(1, to: spring)).isEmpty)
    }
    func testRecurringOccurrencesHaveSeparateStableIDsAndZeroDurationIsVisible() {
        let first = event("2026-09-13T10:00:00Z", "2026-09-13T10:00:00Z")
        let next = event("2026-09-20T10:00:00Z", "2026-09-20T10:00:00Z")
        XCTAssertNotEqual(first.id, next.id)
        XCTAssertEqual(layout().events([first, next], on: first.start), [first])
    }
    func testNewEventRoundsForwardAndCrossesMidnightSafely() {
        let l = layout(), now = date("2026-09-13T23:58:20+08:00")
        XCTAssertEqual(l.defaultStart(on: now, now: now), date("2026-09-14T00:00:00+08:00"))
        XCTAssertEqual(l.defaultStart(on: date("2026-09-20T00:00:00+08:00"), now: now), date("2026-09-20T09:00:00+08:00"))
    }
}

@MainActor final class CalendarStoreTests: XCTestCase {
    private var defaults: UserDefaults!
    private var suite: String!
    override func setUp() { suite = "CalendarStoreTests." + UUID().uuidString; defaults = UserDefaults(suiteName: suite)! }
    override func tearDown() { defaults.removePersistentDomain(forName: suite) }
    private func source(_ id: String) -> CalendarSourceItem { CalendarSourceItem(id: id, title: id, account: "test", isWritable: true, isLocal: true, tint: CalendarTint()) }
    func testOutOfOrderMonthLoadsCannotOverwriteTheLatestResult() async {
        let provider = DeferredCalendarProvider(), store = CalendarStore(provider: provider, defaults: defaults)
        let first = Task { await store.refresh() }
        await provider.waitForRequests(1)
        store.moveMonth(1)
        let second = Task { await store.refresh() }
        await provider.waitForRequests(2)
        provider.requests[1].resume(returning: CalendarSnapshot(calendars: [source("new")]))
        await second.value
        provider.requests[0].resume(returning: CalendarSnapshot(calendars: [source("old")]))
        await first.value
        XCTAssertEqual(store.calendars.map(\.id), ["new"]); XCTAssertFalse(store.isLoading)
    }
    func testPermissionRevocationClearsSnapshotAndRejectsInFlightData() async {
        let provider = DeferredCalendarProvider(), store = CalendarStore(provider: provider, defaults: defaults)
        let task = Task { await store.refresh() }; await provider.waitForRequests(1)
        provider.access = .denied; await store.refresh()
        provider.requests[0].resume(returning: CalendarSnapshot(calendars: [source("private")]))
        await task.value
        XCTAssertEqual(store.access, .denied); XCTAssertTrue(store.calendars.isEmpty); XCTAssertTrue(store.events.isEmpty); XCTAssertFalse(store.canCreate)
    }
    func testHiddenCalendarsPersistButNewCalendarsRemainVisible() async {
        let provider = DeferredCalendarProvider(), store = CalendarStore(provider: provider, defaults: defaults)
        store.setVisible(false, id: "hidden")
        let restored = CalendarStore(provider: provider, defaults: defaults)
        let task = Task { await restored.refresh() }; await provider.waitForRequests(1)
        provider.requests[0].resume(returning: CalendarSnapshot(calendars: [source("hidden"), source("new")]))
        await task.value
        XCTAssertEqual(restored.visibleCalendars.map(\.id), ["new"])
        restored.didSave(start: Date(), calendarID: "hidden")
        XCTAssertEqual(restored.visibleCalendars.count, 2)
    }
    func testWriteOnlyAccessDoesNotQueryOrPretendExistingEventsAreEmpty() async {
        let provider = DeferredCalendarProvider(); provider.access = .writeOnly
        let store = CalendarStore(provider: provider, defaults: defaults)
        await store.refresh()
        XCTAssertEqual(provider.requests.count, 0); XCTAssertEqual(store.access, .writeOnly); XCTAssertFalse(store.canCreate)
    }
}

@MainActor private final class DeferredCalendarProvider: CalendarProviding {
    var access = CalendarAccess.full
    var requests: [CheckedContinuation<CalendarSnapshot, Error>] = []
    func requestAccess() async throws {}
    func snapshot(in interval: DateInterval) async throws -> CalendarSnapshot { try await withCheckedThrowingContinuation { requests.append($0) } }
    func presentation(for occurrence: CalendarOccurrence?, on date: Date, preferredCalendarID: String?) throws -> CalendarPresentation { throw CalendarFailure.previewOnly }
    func waitForRequests(_ count: Int) async {
        for _ in 0..<1000 { if requests.count >= count { return }; await Task.yield() }
        XCTFail("Calendar query did not start")
    }
}

#if targetEnvironment(simulator)
@MainActor final class CalendarEventKitIntegrationTests: XCTestCase {
    func testRealEventKitRoundTripRecurrenceSelectedOccurrenceAndDeletion() async throws {
        guard EKEventStore.authorizationStatus(for: .event) == .fullAccess else { throw XCTSkip("Isolated simulator requires Calendar full access") }
        let provider = SystemCalendarProvider(), store = provider.eventStore
        guard let source = store.sources.first(where: { $0.sourceType == .local }) else { throw XCTSkip("No local calendar source in the simulator") }
        let calendar = EKCalendar(for: .event, eventStore: store)
        calendar.title = "MoriCalendarUnitTest-" + UUID().uuidString; calendar.source = source
        try store.saveCalendar(calendar, commit: true)
        let calendarID = calendar.calendarIdentifier
        defer { if let ownedCalendar = store.calendar(withIdentifier: calendarID) { try? store.removeCalendar(ownedCalendar, commit: true) } }
        let layout = CalendarLayout(), start = layout.defaultStart(on: layout.addingDays(2, to: Date()))
        let event = EKEvent(eventStore: store)
        event.calendar = calendar; event.title = "重复日程集成测试"; event.startDate = start; event.endDate = start.addingTimeInterval(3600)
        event.addAlarm(EKAlarm(relativeOffset: -600))
        event.addRecurrenceRule(EKRecurrenceRule(recurrenceWith: .weekly, interval: 1, end: EKRecurrenceEnd(occurrenceCount: 3)))
        try store.save(event, span: .thisEvent)
        let interval = DateInterval(start: layout.addingDays(-1, to: start), end: layout.addingDays(22, to: start))
        let snapshot = try await provider.snapshot(in: interval)
        let instances = snapshot.events.filter { $0.calendarID == calendarID }.sorted { $0.start < $1.start }
        XCTAssertEqual(instances.count, 3)
        let presentation = try provider.presentation(for: instances[1], on: start, preferredCalendarID: nil)
        XCTAssertEqual(presentation.event.startDate, layout.addingDays(7, to: start), "Must open the selected occurrence, not the first event in the series")
        XCTAssertEqual(presentation.event.alarms?.first?.relativeOffset, -600)
        presentation.event.title = "仅修改第二次"
        try store.save(presentation.event, span: .thisEvent)
        let changed = try await provider.snapshot(in: interval).events.filter { $0.calendarID == calendarID }.sorted { $0.start < $1.start }
        XCTAssertEqual(changed.map(\.title), ["重复日程集成测试", "仅修改第二次", "重复日程集成测试"])
        let removing = try provider.presentation(for: changed[1], on: start, preferredCalendarID: nil)
        try store.remove(removing.event, span: .thisEvent)
        let final = try await provider.snapshot(in: interval)
        XCTAssertEqual(final.events.filter { $0.calendarID == calendarID }.count, 2)
    }
}
#endif
